version: '3.8'

services:
  frontend:
    build: ./lord-of-the-quiz
    ports:
      - '5551:80' # Adjust if using a different port in production
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  backend:
    build: ./nodebackend
    ports:
      - '5552:5552' # Adjust if using a different port in production
volumes:
  mongodb_data:
